name: Automatický sběr dat (Scraper)

on:
  schedule:
    - cron: '0 0 * * *' # Spustí skript každý den o půlnoci
  workflow_dispatch: # Umožňuje ruční spuštění v rozhraní GitHubu

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Stažení repozitáře
      uses: actions/checkout@v4

    - name: Nastavení Pythonu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalace závislostí
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Spuštění stahování dat
      run: python backend/main.py

    - name: Uložení nových dat na GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add data/loans_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace úrokových sazeb" && git push)